#!/usr/bin/env -S uv tool run dotdrop install --profile default --cfg
#
# Add certain executables from this directory to PATH
#
[config]
dotpath = "."
link_dotfile_default = "relative"
link_on_import = "relative"
force_chmod = true

[dotfiles.f_pager]
src = "pager"
dst = "~/.local/bin/pager"
chmod = "755"

[dotfiles.f_vimf]
src = "vimf"
dst = "~/.local/bin/vimf"
chmod = "755"

[dotfiles.f_vimj]
src = "vimj.py" # .py so that doctest passes
dst = "~/.local/bin/vimj"
chmod = "755"

[profiles.default]
dotfiles = ["ALL"]

# Copyright 2025 Keith Maxwell
# SPDX-License-Identifier: CC0-1.0
# bin/path.toml
