line-length = 88
indent-width = 4
target-version = "py313"

[lint]
select = ["ALL"]
ignore = [
  "D203", # incompatible with D211
  "D213", # incompatible with D212
  "I", # prefer usort to ruff isort implementation
  "PT", # prefer unittest style
  "S310", # the rule errors on the "use instead" code from `ruff rule S310`
  "S602", # assume arguments to subprocess.run are validated
  "S603", # assume trusted input  to subprocess.run
  "T201", # print is used for output in command line scripts
]
#
# .ruff.toml
# SPDX-FileCopyrightText: 2025 Keith Maxwell <keith.maxwell@gmail.com>
# SPDX-License-Identifier: CC0-1.0
