version = 1
SPDX-PackageName = "vimfiles"
SPDX-PackageSupplier = "Keith Maxwell <keith.maxwell@gmail.com>"
SPDX-PackageDownloadLocation = "https://codeberg.org/maxwell-k/vimfiles"

[[annotations]]
path = [
  "tests/automated/cog/example.txt",
  "tests/automated/cog/missing.txt",
  "tests/automated/embedme/example.sh",
  "tests/fixtures/**",
]
SPDX-FileCopyrightText = "2020-2025 Keith Maxwell"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
  ".en.utf-8.add",
  ".gitignore",
  ".prettierignore",
  "doc/decisions/.en.utf-8.add",
  "tests/.en.utf-8.add",
  "tests/automated/embedme/example.md",
  "tests/automated/embedme/missing.md",
  "tests/automated/markdown-toc/example.md",
  "tests/automated/markdown-toc/missing.md",
  "tests/manual/.en.utf-8.add",
  "tests/manual/todo.txt",
]
SPDX-FileCopyrightText = "2020-2025 Keith Maxwell"
SPDX-License-Identifier = "CC0-1.0"

# REUSE.toml
# SPDX-FileCopyrightText: 2024 Keith Maxwell <keith.maxwell@gmail.com>
# SPDX-License-Identifier: CC0-1.0
